//! The `html_escape` rule's alternation set — `config/escapeCharacter.ts`.
//!
//! muya builds the rule at `rules.ts:45` as
//!
//! ```js
//! html_escape: new RegExp(`^(${escapeCharacters.join('|')})`, 'i'),
//! ```
//!
//! so this list *is* the rule. It is transcribed verbatim, in source order and
//! including muya's duplicates, because a regex alternation is leftmost-first
//! and "verbatim" is the porting rule (§3). The duplicates are harmless: every
//! entry ends in `;`, so no entry can be a prefix of another and the order
//! cannot change which alternative wins.
//!
//! # Counts
//!
//! M1.md §2 records "538 HTML entity ↔ character pairs". That is the line
//! count of the TypeScript file: **269 entities** paired with 269 characters.
//! Of the 269 entity strings, **252 are distinct** — `&nbsp;`, `&lt;`, `&gt;`,
//! `&amp;` and `&quot;` each appear more than once, mapped to different
//! characters at different indices.
//!
//! That last detail matters for S6 and is recorded here so it is not
//! rediscovered then: `escapeCharactersMap` is built by `reduce` over the same
//! two arrays, so a repeated key is **overwritten by its last occurrence**.
//! The decode map therefore has 252 entries, not 269, and `&nbsp;` decodes to
//! whatever the *last* `&nbsp;` row pairs it with. S1 needs only the keys.

/// The 269 entity strings, in `escapeCharacter.ts` order.
pub(crate) const ESCAPE_CHARACTERS: [&str; 269] = [
    "&quot;",
    "&amp;",
    "&lt;",
    "&gt;",
    "&nbsp;",
    "&ensp;",
    "&emsp;",
    "&nbsp;",
    "&lt;",
    "&gt;",
    "&amp;",
    "&quot;",
    "&copy;",
    "&reg;",
    "&trade;",
    "&times;",
    "&divide;",
    "&nbsp;",
    "&iexcl;",
    "&cent;",
    "&pound;",
    "&curren;",
    "&yen;",
    "&brvbar;",
    "&sect;",
    "&uml;",
    "&copy;",
    "&ordf;",
    "&laquo;",
    "&not;",
    "&shy;",
    "&reg;",
    "&macr;",
    "&deg;",
    "&plusmn;",
    "&sup2;",
    "&sup3;",
    "&acute;",
    "&micro;",
    "&para;",
    "&middot;",
    "&cedil;",
    "&sup1;",
    "&ordm;",
    "&raquo;",
    "&frac14;",
    "&frac12;",
    "&frac34;",
    "&iquest;",
    "&Agrave;",
    "&Aacute;",
    "&Acirc;",
    "&Atilde;",
    "&Auml;",
    "&Aring;",
    "&AElig;",
    "&Ccedil;",
    "&Egrave;",
    "&Eacute;",
    "&Ecirc;",
    "&Euml;",
    "&Igrave;",
    "&Iacute;",
    "&Icirc;",
    "&Iuml;",
    "&ETH;",
    "&Ntilde;",
    "&Ograve;",
    "&Oacute;",
    "&Ocirc;",
    "&Otilde;",
    "&Ouml;",
    "&times;",
    "&Oslash;",
    "&Ugrave;",
    "&Uacute;",
    "&Ucirc;",
    "&Uuml;",
    "&Yacute;",
    "&THORN;",
    "&szlig;",
    "&agrave;",
    "&aacute;",
    "&acirc;",
    "&atilde;",
    "&auml;",
    "&aring;",
    "&aelig;",
    "&ccedil;",
    "&egrave;",
    "&eacute;",
    "&ecirc;",
    "&euml;",
    "&igrave;",
    "&iacute;",
    "&icirc;",
    "&iuml;",
    "&eth;",
    "&ntilde;",
    "&ograve;",
    "&oacute;",
    "&ocirc;",
    "&otilde;",
    "&ouml;",
    "&divide;",
    "&oslash;",
    "&ugrave;",
    "&uacute;",
    "&ucirc;",
    "&uuml;",
    "&yacute;",
    "&thorn;",
    "&yuml;",
    "&fnof;",
    "&Alpha;",
    "&Beta;",
    "&Gamma;",
    "&Delta;",
    "&Epsilon;",
    "&Zeta;",
    "&Eta;",
    "&Theta;",
    "&Iota;",
    "&Kappa;",
    "&Lambda;",
    "&Mu;",
    "&Nu;",
    "&Xi;",
    "&Omicron;",
    "&Pi;",
    "&Rho;",
    "&Sigma;",
    "&Tau;",
    "&Upsilon;",
    "&Phi;",
    "&Chi;",
    "&Psi;",
    "&Omega;",
    "&alpha;",
    "&beta;",
    "&gamma;",
    "&delta;",
    "&epsilon;",
    "&zeta;",
    "&eta;",
    "&theta;",
    "&iota;",
    "&kappa;",
    "&lambda;",
    "&mu;",
    "&nu;",
    "&xi;",
    "&omicron;",
    "&pi;",
    "&rho;",
    "&sigmaf;",
    "&sigma;",
    "&tau;",
    "&upsilon;",
    "&phi;",
    "&chi;",
    "&psi;",
    "&omega;",
    "&thetasym;",
    "&upsih;",
    "&piv;",
    "&bull;",
    "&hellip;",
    "&prime;",
    "&Prime;",
    "&oline;",
    "&frasl;",
    "&weierp;",
    "&image;",
    "&real;",
    "&trade;",
    "&alefsym;",
    "&larr;",
    "&uarr;",
    "&rarr;",
    "&darr;",
    "&harr;",
    "&crarr;",
    "&lArr;",
    "&uArr;",
    "&rArr;",
    "&dArr;",
    "&hArr;",
    "&forall;",
    "&part;",
    "&exist;",
    "&empty;",
    "&nabla;",
    "&isin;",
    "&notin;",
    "&ni;",
    "&prod;",
    "&sum;",
    "&minus;",
    "&lowast;",
    "&radic;",
    "&prop;",
    "&infin;",
    "&ang;",
    "&and;",
    "&or;",
    "&cap;",
    "&cup;",
    "&int;",
    "&there4;",
    "&sim;",
    "&cong;",
    "&asymp;",
    "&ne;",
    "&equiv;",
    "&le;",
    "&ge;",
    "&sub;",
    "&sup;",
    "&nsub;",
    "&sube;",
    "&supe;",
    "&oplus;",
    "&otimes;",
    "&perp;",
    "&sdot;",
    "&lceil;",
    "&rceil;",
    "&lfloor;",
    "&rfloor;",
    "&lang;",
    "&rang;",
    "&loz;",
    "&spades;",
    "&clubs;",
    "&hearts;",
    "&diams;",
    "&quot;",
    "&amp;",
    "&lt;",
    "&gt;",
    "&OElig;",
    "&oelig;",
    "&Scaron;",
    "&scaron;",
    "&Yuml;",
    "&circ;",
    "&tilde;",
    "&ensp;",
    "&emsp;",
    "&thinsp;",
    "&zwnj;",
    "&zwj;",
    "&lrm;",
    "&rlm;",
    "&ndash;",
    "&mdash;",
    "&lsquo;",
    "&rsquo;",
    "&sbquo;",
    "&ldquo;",
    "&rdquo;",
    "&bdquo;",
    "&dagger;",
    "&Dagger;",
    "&permil;",
    "&lsaquo;",
    "&rsaquo;",
    "&euro;",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// The two numbers the module docs rest on, so a bad regeneration of this
    /// table is caught here rather than as a mystery `html_escape` failure.
    #[test]
    fn the_table_has_muyas_269_entries_of_which_252_are_distinct() {
        assert_eq!(ESCAPE_CHARACTERS.len(), 269);
        let mut distinct: Vec<&str> = ESCAPE_CHARACTERS.to_vec();
        distinct.sort_unstable();
        distinct.dedup();
        assert_eq!(distinct.len(), 252);
    }

    /// Every entry is `&` + ASCII alphanumerics + `;`. Two things rest on this:
    /// the alternation needs no regex-metacharacter escaping, and no entry can
    /// be a proper prefix of another.
    #[test]
    fn every_entry_is_an_ascii_named_reference() {
        for entity in ESCAPE_CHARACTERS {
            let body = entity
                .strip_prefix('&')
                .and_then(|e| e.strip_suffix(';'))
                .unwrap_or_else(|| panic!("`{entity}` is not `&…;`"));
            assert!(!body.is_empty(), "`{entity}` has an empty name");
            assert!(
                body.chars().all(|c| c.is_ascii_alphanumeric()),
                "`{entity}` is not ASCII-alphanumeric, so the alternation would \
                 need escaping"
            );
        }
    }
}
