//! The conformance ratchet (RUST-REWRITE-PLAN.md §11.1).
//!
//! # The rule
//!
//! `spec/expected-failures.json` lists the spec examples the engine is known
//! to fail. Two assertions, and they point in opposite directions:
//!
//! - A **listed** example that starts **passing** fails CI. Delist it.
//! - An **unlisted** example that starts **failing** fails CI. Fix it.
//!
//! Net effect: **compliance can only go up.** ~~The floor is muya's current
//! 87.7 % CommonMark 0.31 and 86.3 % GFM 0.29~~ — see [`Suite::floor_percent`],
//! re-baselined at M2 S5. The rest of that sentence held up better than the
//! numbers did: `pulldown-cmark` does handle blocks at >99 %, the port's block
//! sections score 82.7 %, and the residue is in **inlines**.
//!
//! # Status: enforcing, from M2 S5
//!
//! `mt_md::render_to_static_html` answers, so every example runs and every one
//! gets a verdict: **463 / 652 CommonMark and 476 / 672 GFM**.
//!
//! ## What it was, and how it flipped
//!
//! From M0 to M2 S4 that function returned `Unimplemented`, so every example
//! reported [`Verdict::Skipped`] and the runner exited 0 with a loud summary.
//! Nothing was asserted — but the fixtures were loaded, parsed and counted, and
//! the ratchet bookkeeping was unit-tested below, so the things that rot
//! silently (a malformed fixture file, a stale expected-failures list, a
//! broken JSON shape) were caught from day one.
//!
//! There was nothing to flip: the first `Ok` stopped producing
//! [`Verdict::Skipped`] and the ratchet began enforcing on the very same run,
//! which is M0 decision 7 working as designed. What S5 had to do once, in one
//! commit, is `spec/README.md`'s four steps — regenerate with `--update`, read
//! the diff in **both** directions, rewrite `spec/conformance.md`, and raise
//! [`Suite::floor_percent`] to the measured rate.

use std::collections::BTreeSet;
use std::fmt;
use std::path::{Path, PathBuf};

use crate::html::normalize_html;

/// One spec example, matching the JSON shape of both fixture files:
/// `{ markdown, html, section, number }`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Example {
    pub markdown: String,
    pub html: String,
    pub section: String,
    pub number: u32,
}

/// Which suite an example belongs to. The key names match the top-level keys
/// in `expected-failures.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Suite {
    CommonMark,
    Gfm,
}

impl Suite {
    pub const ALL: [Suite; 2] = [Suite::CommonMark, Suite::Gfm];

    /// The key under which this suite's failures are listed.
    pub fn key(self) -> &'static str {
        match self {
            Suite::CommonMark => "commonmark",
            Suite::Gfm => "gfm",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Suite::CommonMark => "CommonMark 0.31",
            Suite::Gfm => "GFM 0.29-gfm",
        }
    }

    /// The fixture file, relative to `spec/`.
    ///
    /// The GFM file is copied verbatim from muya. The CommonMark file is
    /// generated by `tools/vendor-commonmark-spec.mjs`, because muya's
    /// `commonmark.spec.ts` pulls those examples from the `commonmark-spec`
    /// npm package at test time rather than committing them — see that
    /// script's header for why that gap had to be closed.
    pub fn fixture(self) -> &'static str {
        match self {
            Suite::CommonMark => "fixtures/commonmark-spec-0.31.json",
            Suite::Gfm => "fixtures/gfm-spec-0.29-gfm.json",
        }
    }

    /// The pass-rate floor from `spec/conformance.md`. Compliance may not fall
    /// below this, ever.
    ///
    /// # Re-baselined at M2 S5, and this is the one-way door
    ///
    /// It was **87.7 / 86.3** from M0 until S5, and those were *muya's*
    /// numbers: `getHighlightHtml`'s, which is `marked` plus Prism plus
    /// DOMPurify. docs/M2.md §4 C3 decided `render_to_static_html` renders
    /// through `Document` instead and said in as many words that this
    /// **guarantees** the number differs; §5 D5 decided that the regenerated
    /// list and this constant move in the same commit, so that a later
    /// regression cannot eat the margin between them without the backstop
    /// firing.
    ///
    /// **463 of 652 and 476 of 672** — 71.01 % and 70.83 %, truncated to a
    /// tenth. Truncated rather than rounded, because a floor above the
    /// measured rate is a gate no commit can pass; `spec/conformance.md`
    /// carries the per-section breakdown and docs/M2.md §6 carries the
    /// argument for every one of the 231 entries the list gained.
    ///
    /// This is a **backstop and not a review** (`spec/README.md` says so in
    /// those words). The thing that actually holds the line is the ratchet:
    /// with the list regenerated to exactly today's failures, an unlisted
    /// example that starts failing is an `UnexpectedFailure` long before the
    /// aggregate moves.
    pub fn floor_percent(self) -> f64 {
        match self {
            Suite::CommonMark => 71.0,
            Suite::Gfm => 70.8,
        }
    }
}

impl fmt::Display for Suite {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

/// What the ratchet decided about a single example.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Unlisted and passing. The desired state.
    Pass,
    /// Listed and still failing. Acceptable — it is on the list.
    ExpectedFailure,
    /// Listed but now passing. **Fails CI**: delist it, because the list is
    /// the floor and a stale entry lets compliance quietly fall back later.
    UnexpectedPass,
    /// Unlisted and now failing. **Fails CI**: this is a regression.
    UnexpectedFailure,
    /// The engine does not implement rendering yet. Neither a pass nor a
    /// failure; CI stays green and says so.
    Skipped,
}

impl Verdict {
    /// Decide an example's verdict. This function *is* the ratchet.
    pub fn decide(listed: bool, outcome: Option<bool>) -> Verdict {
        match (listed, outcome) {
            (_, None) => Verdict::Skipped,
            (true, Some(true)) => Verdict::UnexpectedPass,
            (true, Some(false)) => Verdict::ExpectedFailure,
            (false, Some(true)) => Verdict::Pass,
            (false, Some(false)) => Verdict::UnexpectedFailure,
        }
    }

    /// Whether this verdict must fail the build.
    pub fn is_ci_failure(self) -> bool {
        matches!(self, Verdict::UnexpectedPass | Verdict::UnexpectedFailure)
    }
}

/// One section's tally, for the per-section breakdown `spec/conformance.md`
/// is written from.
#[derive(Debug, Default, Clone)]
pub struct SectionReport {
    pub section: String,
    pub total: usize,
    pub passed: usize,
}

impl SectionReport {
    pub fn pass_rate(&self) -> f64 {
        if self.total == 0 {
            return 0.0;
        }
        (self.passed as f64 / self.total as f64) * 100.0
    }
}

/// The outcome of running one suite.
#[derive(Debug, Default, Clone)]
pub struct SuiteReport {
    pub total: usize,
    pub passed: usize,
    pub expected_failures: usize,
    pub skipped: usize,
    /// Listed but now passing — delist these.
    pub unexpected_passes: Vec<u32>,
    /// Unlisted but now failing — regressions.
    pub unexpected_failures: Vec<u32>,
    /// Numbers in `expected-failures.json` that no example has. A stale list
    /// entry is not a build failure, but it is always a mistake worth naming.
    pub stale_listings: Vec<u32>,
    /// How many examples produced a verdict that must fail the build.
    pub ci_failures: usize,
    /// Every example that failed, listed or not, in document order. This is
    /// what `--update` writes, and what M2.md §5 D5 requires be *read* rather
    /// than accepted — the re-baseline is a one-way door.
    pub failing: Vec<u32>,
    /// Per-section tallies, in first-appearance order.
    pub sections: Vec<SectionReport>,
}

impl SuiteReport {
    /// Pass rate over the examples that actually ran.
    pub fn pass_rate(&self) -> f64 {
        let ran = self.total - self.skipped;
        if ran == 0 {
            return 0.0;
        }
        (self.passed as f64 / self.total as f64) * 100.0
    }

    pub fn everything_skipped(&self) -> bool {
        self.total > 0 && self.skipped == self.total
    }

    pub fn is_ci_failure(&self) -> bool {
        self.ci_failures > 0
    }
}

/// Load `spec/expected-failures.json` and return the listed numbers for a suite.
pub fn load_expected_failures(spec_dir: &Path, suite: Suite) -> Result<BTreeSet<u32>, String> {
    let path = spec_dir.join("expected-failures.json");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let value: serde_json::Value =
        serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;

    let list = value
        .get(suite.key())
        .ok_or_else(|| format!("{}: missing key {:?}", path.display(), suite.key()))?
        .as_array()
        .ok_or_else(|| format!("{}: {:?} is not an array", path.display(), suite.key()))?;

    list.iter()
        .map(|v| {
            v.as_u64()
                .and_then(|n| u32::try_from(n).ok())
                .ok_or_else(|| format!("{}: {v} is not an example number", path.display()))
        })
        .collect()
}

/// Load a suite's fixtures.
pub fn load_examples(spec_dir: &Path, suite: Suite) -> Result<Vec<Example>, String> {
    let path = spec_dir.join(suite.fixture());
    let text = std::fs::read_to_string(&path).map_err(|e| {
        let mut msg = format!("cannot read {}: {e}", path.display());
        if suite == Suite::CommonMark {
            msg.push_str(
                "\nThe CommonMark fixtures are generated, not copied. Run:\n\
                 \x20 node tools/vendor-commonmark-spec.mjs",
            );
        }
        msg
    })?;
    let raw: Vec<serde_json::Value> =
        serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;

    raw.iter()
        .enumerate()
        .map(|(i, v)| {
            let field = |name: &str| -> Result<&serde_json::Value, String> {
                v.get(name)
                    .ok_or_else(|| format!("{}: example {i} has no {name:?}", path.display()))
            };
            Ok(Example {
                markdown: field("markdown")?.as_str().unwrap_or_default().to_string(),
                html: field("html")?.as_str().unwrap_or_default().to_string(),
                section: field("section")?.as_str().unwrap_or_default().to_string(),
                number: field("number")?.as_u64().unwrap_or_default() as u32,
            })
        })
        .collect()
}

/// Run one example. `None` means the engine is not implemented yet.
fn run_example(example: &Example) -> Option<bool> {
    // muya's spec runners call `renderToStaticHTML(..., { sanitize: false })`
    // deliberately: they measure the *parser's* compliance, not the
    // sanitiser. CommonMark §6.9 "Raw HTML" explicitly tests that unknown
    // tags like `<bab>` are preserved, which any reasonable sanitiser strips.
    match mt_md::render_to_static_html(&example.markdown, mt_md::Options::SPEC, false) {
        Err(mt_md::Unimplemented) => None,
        Ok(actual) => Some(normalize_html(&actual) == normalize_html(&example.html)),
    }
}

/// Run one suite's ratchet.
pub fn run_suite(spec_dir: &Path, suite: Suite) -> Result<SuiteReport, String> {
    let listed = load_expected_failures(spec_dir, suite)?;
    let examples = load_examples(spec_dir, suite)?;

    let mut report = SuiteReport {
        total: examples.len(),
        ..Default::default()
    };

    let mut seen: BTreeSet<u32> = BTreeSet::new();
    for example in &examples {
        seen.insert(example.number);
        let outcome = run_example(example);
        if outcome == Some(false) {
            report.failing.push(example.number);
        }
        if let Some(passed) = outcome {
            let section = match report.sections.last_mut() {
                Some(last) if last.section == example.section => last,
                _ => {
                    report.sections.push(SectionReport {
                        section: example.section.clone(),
                        ..Default::default()
                    });
                    report.sections.last_mut().expect("just pushed")
                }
            };
            section.total += 1;
            section.passed += usize::from(passed);
        }
        let verdict = Verdict::decide(listed.contains(&example.number), outcome);
        if verdict.is_ci_failure() {
            report.ci_failures += 1;
        }
        match verdict {
            Verdict::Pass => report.passed += 1,
            Verdict::ExpectedFailure => report.expected_failures += 1,
            Verdict::Skipped => report.skipped += 1,
            Verdict::UnexpectedPass => {
                report.passed += 1;
                report.unexpected_passes.push(example.number);
            }
            Verdict::UnexpectedFailure => report.unexpected_failures.push(example.number),
        }
    }

    report.stale_listings = listed.difference(&seen).copied().collect();
    Ok(report)
}

/// `cargo xtask conformance`.
pub fn main(repo_root: &Path, args: &[String]) -> Result<i32, String> {
    let spec_dir: PathBuf = repo_root.join("spec");
    let mut failed = false;
    let mut all_skipped = true;
    let mut only: Option<Suite> = None;
    let mut sections = false;
    let mut update = false;
    let mut show: Vec<u32> = Vec::new();

    let mut rest = args.iter();
    while let Some(arg) = rest.next() {
        match arg.as_str() {
            "--suite" => {
                let name = rest.next().ok_or("--suite requires commonmark|gfm")?;
                only = Some(match name.as_str() {
                    "commonmark" => Suite::CommonMark,
                    "gfm" => Suite::Gfm,
                    other => return Err(format!("unknown suite: {other}")),
                });
            }
            "--sections" => sections = true,
            "--show" => {
                let numbers = rest
                    .next()
                    .ok_or("--show requires a comma-separated list")?;
                show = numbers
                    .split(',')
                    .map(|n| n.trim().parse::<u32>().map_err(|e| format!("{n}: {e}")))
                    .collect::<Result<Vec<u32>, String>>()?;
            }
            "--update" => update = true,
            other => return Err(format!("unrecognised argument: {other}")),
        }
    }

    println!("conformance ratchet — RUST-REWRITE-PLAN.md §11.1");
    println!("spec dir: {}", spec_dir.display());
    println!();

    if !show.is_empty() {
        for suite in Suite::ALL {
            if only.is_some_and(|wanted| wanted != suite) {
                continue;
            }
            for example in load_examples(&spec_dir, suite)? {
                if !show.contains(&example.number) {
                    continue;
                }
                let actual =
                    mt_md::render_to_static_html(&example.markdown, mt_md::Options::SPEC, false)
                        .unwrap_or_else(|_| "<unimplemented>".to_string());
                println!(
                    "--- {} #{} ({})",
                    suite.label(),
                    example.number,
                    example.section
                );
                println!("  markdown  {:?}", example.markdown);
                println!("  expected  {:?}", normalize_html(&example.html));
                println!("  actual    {:?}", normalize_html(&actual));
                println!();
            }
        }
        return Ok(0);
    }

    let mut regenerated: Vec<(Suite, Vec<u32>)> = Vec::new();

    for suite in Suite::ALL {
        if only.is_some_and(|wanted| wanted != suite) {
            continue;
        }
        let report = run_suite(&spec_dir, suite)?;
        all_skipped &= report.everything_skipped();
        regenerated.push((suite, report.failing.clone()));

        println!("{}", suite.label());
        println!("  examples          {}", report.total);
        if report.everything_skipped() {
            println!(
                "  SKIPPED           all {} (mt_md has no parser yet — M2)",
                report.total
            );
        } else {
            println!(
                "  passed            {} ({:.1} %, floor {:.1} %)",
                report.passed,
                report.pass_rate(),
                suite.floor_percent()
            );
            println!("  expected failures {}", report.expected_failures);
            if report.skipped > 0 {
                println!("  skipped           {}", report.skipped);
            }
            if report.pass_rate() + f64::EPSILON < suite.floor_percent() {
                println!(
                    "  FAIL              pass rate is below the {:.1} % floor from spec/conformance.md",
                    suite.floor_percent()
                );
                failed = true;
            }
        }

        failed |= report.is_ci_failure();

        if !report.unexpected_passes.is_empty() {
            println!(
                "  FAIL              {} listed example(s) now PASS. Compliance only goes up —\n\
                 \x20                   remove them from spec/expected-failures.json:\n\
                 \x20                   {:?}",
                report.unexpected_passes.len(),
                report.unexpected_passes
            );
        }
        if !report.unexpected_failures.is_empty() {
            println!(
                "  FAIL              {} unlisted example(s) now FAIL. This is a regression:\n\
                 \x20                   {:?}",
                report.unexpected_failures.len(),
                report.unexpected_failures
            );
        }
        if !report.stale_listings.is_empty() {
            println!(
                "  note              {} listed number(s) match no example (stale list): {:?}",
                report.stale_listings.len(),
                report.stale_listings
            );
        }
        if sections && !report.everything_skipped() {
            println!();
            for section in &report.sections {
                println!(
                    "    {:>4} / {:>4}  {:>5.1} %  {}",
                    section.passed,
                    section.total,
                    section.pass_rate(),
                    section.section
                );
            }
        }
        println!();
    }

    if update {
        write_expected_failures(&spec_dir, &regenerated, only.is_none())?;
        println!(
            "expected-failures.json rewritten from the measured results.\n\
             M2.md §5 D5: read the diff in BOTH directions, argue every addition\n\
             individually in the same commit, and raise floor_percent() to the\n\
             measured rate in that same commit."
        );
        return Ok(0);
    }

    if all_skipped {
        println!(
            "All examples skipped: mt_md::render_to_static_html is a stub until M2.\n\
             The ratchet is wired and the fixtures load — it begins enforcing on the\n\
             first run where that function returns Ok. See spec/README.md."
        );
    }

    Ok(if failed { 1 } else { 0 })
}

/// Rewrite `spec/expected-failures.json` from the measured results.
///
/// `spec/README.md` step 1, and M2.md §5 D5's one-way door. Deliberately
/// refuses to run for a single suite: rewriting one key from a run that
/// measured only one suite would leave the other key describing a different
/// commit, and the file has no way to say so.
fn write_expected_failures(
    spec_dir: &Path,
    measured: &[(Suite, Vec<u32>)],
    both_suites: bool,
) -> Result<(), String> {
    if !both_suites {
        return Err("--update rewrites both keys of expected-failures.json, \
                    so it cannot be combined with --suite"
            .to_string());
    }
    let mut out = String::from("{\n");
    for (index, (suite, failing)) in measured.iter().enumerate() {
        out.push_str(&format!("  \"{}\": [\n", suite.key()));
        let numbers: Vec<String> = failing.iter().map(u32::to_string).collect();
        for (row, chunk) in numbers.chunks(10).enumerate() {
            let last = (row + 1) * 10 >= numbers.len();
            out.push_str("    ");
            out.push_str(&chunk.join(", "));
            out.push_str(if last { "\n" } else { ",\n" });
        }
        out.push_str("  ]");
        out.push_str(if index + 1 == measured.len() {
            "\n"
        } else {
            ",\n"
        });
    }
    out.push_str("}\n");
    let path = spec_dir.join("expected-failures.json");
    std::fs::write(&path, out).map_err(|e| format!("cannot write {}: {e}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec_dir() -> PathBuf {
        crate::repo_root().join("spec")
    }

    // --- the ratchet contract, tested against synthetic inputs -------------

    #[test]
    fn listed_and_failing_is_fine() {
        assert_eq!(Verdict::decide(true, Some(false)), Verdict::ExpectedFailure);
        assert!(!Verdict::ExpectedFailure.is_ci_failure());
    }

    #[test]
    fn unlisted_and_passing_is_fine() {
        assert_eq!(Verdict::decide(false, Some(true)), Verdict::Pass);
        assert!(!Verdict::Pass.is_ci_failure());
    }

    /// The half of the ratchet people forget: getting *better* must also fail
    /// the build, so the list is forced back down.
    #[test]
    fn listed_but_now_passing_fails_ci() {
        assert_eq!(Verdict::decide(true, Some(true)), Verdict::UnexpectedPass);
        assert!(Verdict::UnexpectedPass.is_ci_failure());
    }

    #[test]
    fn unlisted_but_now_failing_fails_ci() {
        assert_eq!(
            Verdict::decide(false, Some(false)),
            Verdict::UnexpectedFailure
        );
        assert!(Verdict::UnexpectedFailure.is_ci_failure());
    }

    #[test]
    fn unimplemented_is_skipped_whether_listed_or_not() {
        assert_eq!(Verdict::decide(true, None), Verdict::Skipped);
        assert_eq!(Verdict::decide(false, None), Verdict::Skipped);
        assert!(!Verdict::Skipped.is_ci_failure());
    }

    // --- the fixtures actually load, at the sizes conformance.md states ----

    #[test]
    fn commonmark_fixtures_load() {
        let examples = load_examples(&spec_dir(), Suite::CommonMark).expect("load CommonMark");
        assert_eq!(
            examples.len(),
            652,
            "spec/conformance.md records 652 CommonMark 0.31 examples"
        );
        assert!(examples.iter().all(|e| e.number > 0));
    }

    #[test]
    fn gfm_fixtures_load() {
        let examples = load_examples(&spec_dir(), Suite::Gfm).expect("load GFM");
        assert_eq!(
            examples.len(),
            672,
            "spec/conformance.md records 672 GFM 0.29-gfm examples"
        );
        assert!(examples.iter().all(|e| e.number > 0));
    }

    #[test]
    fn expected_failures_parse_for_both_suites() {
        let cm = load_expected_failures(&spec_dir(), Suite::CommonMark).expect("commonmark list");
        let gfm = load_expected_failures(&spec_dir(), Suite::Gfm).expect("gfm list");
        assert!(!cm.is_empty());
        assert!(!gfm.is_empty());
    }

    /// Every listed number must name a real example. A number that names
    /// nothing is either a typo or a fixture-version mismatch, and it silently
    /// weakens the ratchet by one example.
    #[test]
    fn every_listed_failure_names_a_real_example() {
        for suite in Suite::ALL {
            let listed = load_expected_failures(&spec_dir(), suite).expect("list");
            let numbers: BTreeSet<u32> = load_examples(&spec_dir(), suite)
                .expect("examples")
                .iter()
                .map(|e| e.number)
                .collect();
            let stale: Vec<u32> = listed.difference(&numbers).copied().collect();
            assert!(stale.is_empty(), "{suite}: stale listings {stale:?}");
        }
    }

    /// The floors are the M2 exit gate, restated from §9 and spec/conformance.md.
    /// Listed failures cap the achievable rate, so the list must leave room to
    /// clear the floor.
    #[test]
    fn expected_failure_lists_leave_room_above_the_floor() {
        for suite in Suite::ALL {
            let listed = load_expected_failures(&spec_dir(), suite)
                .expect("list")
                .len();
            let total = load_examples(&spec_dir(), suite).expect("examples").len();
            let ceiling = ((total - listed) as f64 / total as f64) * 100.0;
            assert!(
                ceiling >= suite.floor_percent(),
                "{suite}: {listed} listed failures cap the pass rate at {ceiling:.1} %, \
                 below the {:.1} % floor",
                suite.floor_percent()
            );
        }
    }

    // `every_suite_is_skipped_at_m0` lived here from M0 until M2 S5. It made
    // the transition deliberate — it failed the moment
    // `mt_md::render_to_static_html` first returned `Ok`, and its message
    // pointed at spec/README.md, whose step 4 names deleting it as part of the
    // re-baseline. It is gone rather than inverted, because the state it
    // asserted cannot come back: the door only opens once.

    /// The other half of that door, and the reason the deleted test above is
    /// not simply missing.
    ///
    /// A suite that goes back to reporting `Skipped` **wholesale** has stopped
    /// measuring anything, and the ratchet's own four rows cannot see that:
    /// every verdict would be `Skipped`, none of them a CI failure, and the
    /// run would exit 0 with a loud summary saying so — which is exactly what
    /// M0 through S4 did on purpose. From S5 that summary would be a lie.
    #[test]
    fn neither_suite_is_skipped_from_s5_on() {
        for suite in Suite::ALL {
            let report = run_suite(&spec_dir(), suite).expect("run");
            assert_eq!(
                report.skipped, 0,
                "{suite}: the renderer answered for every example at S5, so a \
                 skip here means an entry point closed again"
            );
            assert!(report.passed > 0);
        }
    }
}
