//! The conformance ratchet (RUST-REWRITE-PLAN.md §11.1).
//!
//! # The rule
//!
//! `spec/expected-failures.json` lists the spec examples the engine is known
//! to fail. Two assertions, and they point in opposite directions:
//!
//! - A **listed** example that starts **passing** fails CI. Delist it.
//! - An **unlisted** example that starts **failing** fails CI. Fix it.
//!
//! Net effect: **compliance can only go up.** The floor is muya's current
//! 87.7 % CommonMark 0.31 and 86.3 % GFM 0.29, which is also the M2 exit gate
//! (§9). Because `pulldown-cmark` handles blocks at >99 %, the realistic
//! target is meaningfully higher and most residual failures should be in
//! block-tree mapping rather than in parsing.
//!
//! # M0 status: skipped-but-present
//!
//! `mt_md::render_to_static_html` returns `Unimplemented`, so every example
//! reports [`Verdict::Skipped`] and the runner exits 0 with a loud summary.
//! Nothing is asserted yet — but the fixtures are loaded, parsed, and counted,
//! and the ratchet bookkeeping itself is unit-tested below. That means the
//! things that rot silently (a malformed fixture file, a stale
//! expected-failures list, a broken JSON shape) are caught from day one.
//!
//! ## Flipping it on at M2
//!
//! There is nothing to flip. When `render_to_static_html` starts returning
//! `Ok`, [`Verdict::Skipped`] stops being produced and the ratchet begins
//! enforcing on the very same run — see `spec/README.md`. The one thing to do
//! at that point is re-baseline: run `cargo xtask conformance --update` to
//! rewrite `expected-failures.json` from the actual results, review the diff
//! **carefully** (it is the new floor and it can never be raised again), and
//! commit it with an updated `spec/conformance.md`.

use std::collections::BTreeSet;
use std::fmt;
use std::path::{Path, PathBuf};

use crate::html::normalize_html;

/// One spec example, matching the JSON shape of both fixture files:
/// `{ markdown, html, section, number }`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Example {
    pub markdown: String,
    pub html: String,
    pub section: String,
    pub number: u32,
}

/// Which suite an example belongs to. The key names match the top-level keys
/// in `expected-failures.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Suite {
    CommonMark,
    Gfm,
}

impl Suite {
    pub const ALL: [Suite; 2] = [Suite::CommonMark, Suite::Gfm];

    /// The key under which this suite's failures are listed.
    pub fn key(self) -> &'static str {
        match self {
            Suite::CommonMark => "commonmark",
            Suite::Gfm => "gfm",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Suite::CommonMark => "CommonMark 0.31",
            Suite::Gfm => "GFM 0.29-gfm",
        }
    }

    /// The fixture file, relative to `spec/`.
    ///
    /// The GFM file is copied verbatim from muya. The CommonMark file is
    /// generated by `tools/vendor-commonmark-spec.mjs`, because muya's
    /// `commonmark.spec.ts` pulls those examples from the `commonmark-spec`
    /// npm package at test time rather than committing them — see that
    /// script's header for why that gap had to be closed.
    pub fn fixture(self) -> &'static str {
        match self {
            Suite::CommonMark => "fixtures/commonmark-spec-0.31.json",
            Suite::Gfm => "fixtures/gfm-spec-0.29-gfm.json",
        }
    }

    /// The pass-rate floor from `spec/conformance.md`. Compliance may not fall
    /// below this, ever.
    pub fn floor_percent(self) -> f64 {
        match self {
            Suite::CommonMark => 87.7,
            Suite::Gfm => 86.3,
        }
    }
}

impl fmt::Display for Suite {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.label())
    }
}

/// What the ratchet decided about a single example.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Verdict {
    /// Unlisted and passing. The desired state.
    Pass,
    /// Listed and still failing. Acceptable — it is on the list.
    ExpectedFailure,
    /// Listed but now passing. **Fails CI**: delist it, because the list is
    /// the floor and a stale entry lets compliance quietly fall back later.
    UnexpectedPass,
    /// Unlisted and now failing. **Fails CI**: this is a regression.
    UnexpectedFailure,
    /// The engine does not implement rendering yet. Neither a pass nor a
    /// failure; CI stays green and says so.
    Skipped,
}

impl Verdict {
    /// Decide an example's verdict. This function *is* the ratchet.
    pub fn decide(listed: bool, outcome: Option<bool>) -> Verdict {
        match (listed, outcome) {
            (_, None) => Verdict::Skipped,
            (true, Some(true)) => Verdict::UnexpectedPass,
            (true, Some(false)) => Verdict::ExpectedFailure,
            (false, Some(true)) => Verdict::Pass,
            (false, Some(false)) => Verdict::UnexpectedFailure,
        }
    }

    /// Whether this verdict must fail the build.
    pub fn is_ci_failure(self) -> bool {
        matches!(self, Verdict::UnexpectedPass | Verdict::UnexpectedFailure)
    }
}

/// The outcome of running one suite.
#[derive(Debug, Default, Clone)]
pub struct SuiteReport {
    pub total: usize,
    pub passed: usize,
    pub expected_failures: usize,
    pub skipped: usize,
    /// Listed but now passing — delist these.
    pub unexpected_passes: Vec<u32>,
    /// Unlisted but now failing — regressions.
    pub unexpected_failures: Vec<u32>,
    /// Numbers in `expected-failures.json` that no example has. A stale list
    /// entry is not a build failure, but it is always a mistake worth naming.
    pub stale_listings: Vec<u32>,
    /// How many examples produced a verdict that must fail the build.
    pub ci_failures: usize,
}

impl SuiteReport {
    /// Pass rate over the examples that actually ran.
    pub fn pass_rate(&self) -> f64 {
        let ran = self.total - self.skipped;
        if ran == 0 {
            return 0.0;
        }
        (self.passed as f64 / self.total as f64) * 100.0
    }

    pub fn everything_skipped(&self) -> bool {
        self.total > 0 && self.skipped == self.total
    }

    pub fn is_ci_failure(&self) -> bool {
        self.ci_failures > 0
    }
}

/// Load `spec/expected-failures.json` and return the listed numbers for a suite.
pub fn load_expected_failures(spec_dir: &Path, suite: Suite) -> Result<BTreeSet<u32>, String> {
    let path = spec_dir.join("expected-failures.json");
    let text = std::fs::read_to_string(&path)
        .map_err(|e| format!("cannot read {}: {e}", path.display()))?;
    let value: serde_json::Value =
        serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;

    let list = value
        .get(suite.key())
        .ok_or_else(|| format!("{}: missing key {:?}", path.display(), suite.key()))?
        .as_array()
        .ok_or_else(|| format!("{}: {:?} is not an array", path.display(), suite.key()))?;

    list.iter()
        .map(|v| {
            v.as_u64()
                .and_then(|n| u32::try_from(n).ok())
                .ok_or_else(|| format!("{}: {v} is not an example number", path.display()))
        })
        .collect()
}

/// Load a suite's fixtures.
pub fn load_examples(spec_dir: &Path, suite: Suite) -> Result<Vec<Example>, String> {
    let path = spec_dir.join(suite.fixture());
    let text = std::fs::read_to_string(&path).map_err(|e| {
        let mut msg = format!("cannot read {}: {e}", path.display());
        if suite == Suite::CommonMark {
            msg.push_str(
                "\nThe CommonMark fixtures are generated, not copied. Run:\n\
                 \x20 node tools/vendor-commonmark-spec.mjs",
            );
        }
        msg
    })?;
    let raw: Vec<serde_json::Value> =
        serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;

    raw.iter()
        .enumerate()
        .map(|(i, v)| {
            let field = |name: &str| -> Result<&serde_json::Value, String> {
                v.get(name)
                    .ok_or_else(|| format!("{}: example {i} has no {name:?}", path.display()))
            };
            Ok(Example {
                markdown: field("markdown")?.as_str().unwrap_or_default().to_string(),
                html: field("html")?.as_str().unwrap_or_default().to_string(),
                section: field("section")?.as_str().unwrap_or_default().to_string(),
                number: field("number")?.as_u64().unwrap_or_default() as u32,
            })
        })
        .collect()
}

/// Run one example. `None` means the engine is not implemented yet.
fn run_example(example: &Example) -> Option<bool> {
    // muya's spec runners call `renderToStaticHTML(..., { sanitize: false })`
    // deliberately: they measure the *parser's* compliance, not the
    // sanitiser. CommonMark §6.9 "Raw HTML" explicitly tests that unknown
    // tags like `<bab>` are preserved, which any reasonable sanitiser strips.
    match mt_md::render_to_static_html(&example.markdown, mt_md::Options::SPEC, false) {
        Err(mt_md::Unimplemented) => None,
        Ok(actual) => Some(normalize_html(&actual) == normalize_html(&example.html)),
    }
}

/// Run one suite's ratchet.
pub fn run_suite(spec_dir: &Path, suite: Suite) -> Result<SuiteReport, String> {
    let listed = load_expected_failures(spec_dir, suite)?;
    let examples = load_examples(spec_dir, suite)?;

    let mut report = SuiteReport {
        total: examples.len(),
        ..Default::default()
    };

    let mut seen: BTreeSet<u32> = BTreeSet::new();
    for example in &examples {
        seen.insert(example.number);
        let verdict = Verdict::decide(listed.contains(&example.number), run_example(example));
        if verdict.is_ci_failure() {
            report.ci_failures += 1;
        }
        match verdict {
            Verdict::Pass => report.passed += 1,
            Verdict::ExpectedFailure => report.expected_failures += 1,
            Verdict::Skipped => report.skipped += 1,
            Verdict::UnexpectedPass => {
                report.passed += 1;
                report.unexpected_passes.push(example.number);
            }
            Verdict::UnexpectedFailure => report.unexpected_failures.push(example.number),
        }
    }

    report.stale_listings = listed.difference(&seen).copied().collect();
    Ok(report)
}

/// `cargo xtask conformance`.
pub fn main(repo_root: &Path) -> Result<i32, String> {
    let spec_dir: PathBuf = repo_root.join("spec");
    let mut failed = false;
    let mut all_skipped = true;

    println!("conformance ratchet — RUST-REWRITE-PLAN.md §11.1");
    println!("spec dir: {}", spec_dir.display());
    println!();

    for suite in Suite::ALL {
        let report = run_suite(&spec_dir, suite)?;
        all_skipped &= report.everything_skipped();

        println!("{}", suite.label());
        println!("  examples          {}", report.total);
        if report.everything_skipped() {
            println!(
                "  SKIPPED           all {} (mt_md has no parser yet — M2)",
                report.total
            );
        } else {
            println!(
                "  passed            {} ({:.1} %, floor {:.1} %)",
                report.passed,
                report.pass_rate(),
                suite.floor_percent()
            );
            println!("  expected failures {}", report.expected_failures);
            if report.skipped > 0 {
                println!("  skipped           {}", report.skipped);
            }
            if report.pass_rate() + f64::EPSILON < suite.floor_percent() {
                println!(
                    "  FAIL              pass rate is below the {:.1} % floor from spec/conformance.md",
                    suite.floor_percent()
                );
                failed = true;
            }
        }

        failed |= report.is_ci_failure();

        if !report.unexpected_passes.is_empty() {
            println!(
                "  FAIL              {} listed example(s) now PASS. Compliance only goes up —\n\
                 \x20                   remove them from spec/expected-failures.json:\n\
                 \x20                   {:?}",
                report.unexpected_passes.len(),
                report.unexpected_passes
            );
        }
        if !report.unexpected_failures.is_empty() {
            println!(
                "  FAIL              {} unlisted example(s) now FAIL. This is a regression:\n\
                 \x20                   {:?}",
                report.unexpected_failures.len(),
                report.unexpected_failures
            );
        }
        if !report.stale_listings.is_empty() {
            println!(
                "  note              {} listed number(s) match no example (stale list): {:?}",
                report.stale_listings.len(),
                report.stale_listings
            );
        }
        println!();
    }

    if all_skipped {
        println!(
            "All examples skipped: mt_md::render_to_static_html is a stub until M2.\n\
             The ratchet is wired and the fixtures load — it begins enforcing on the\n\
             first run where that function returns Ok. See spec/README.md."
        );
    }

    Ok(if failed { 1 } else { 0 })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn spec_dir() -> PathBuf {
        crate::repo_root().join("spec")
    }

    // --- the ratchet contract, tested against synthetic inputs -------------

    #[test]
    fn listed_and_failing_is_fine() {
        assert_eq!(Verdict::decide(true, Some(false)), Verdict::ExpectedFailure);
        assert!(!Verdict::ExpectedFailure.is_ci_failure());
    }

    #[test]
    fn unlisted_and_passing_is_fine() {
        assert_eq!(Verdict::decide(false, Some(true)), Verdict::Pass);
        assert!(!Verdict::Pass.is_ci_failure());
    }

    /// The half of the ratchet people forget: getting *better* must also fail
    /// the build, so the list is forced back down.
    #[test]
    fn listed_but_now_passing_fails_ci() {
        assert_eq!(Verdict::decide(true, Some(true)), Verdict::UnexpectedPass);
        assert!(Verdict::UnexpectedPass.is_ci_failure());
    }

    #[test]
    fn unlisted_but_now_failing_fails_ci() {
        assert_eq!(
            Verdict::decide(false, Some(false)),
            Verdict::UnexpectedFailure
        );
        assert!(Verdict::UnexpectedFailure.is_ci_failure());
    }

    #[test]
    fn unimplemented_is_skipped_whether_listed_or_not() {
        assert_eq!(Verdict::decide(true, None), Verdict::Skipped);
        assert_eq!(Verdict::decide(false, None), Verdict::Skipped);
        assert!(!Verdict::Skipped.is_ci_failure());
    }

    // --- the fixtures actually load, at the sizes conformance.md states ----

    #[test]
    fn commonmark_fixtures_load() {
        let examples = load_examples(&spec_dir(), Suite::CommonMark).expect("load CommonMark");
        assert_eq!(
            examples.len(),
            652,
            "spec/conformance.md records 652 CommonMark 0.31 examples"
        );
        assert!(examples.iter().all(|e| e.number > 0));
    }

    #[test]
    fn gfm_fixtures_load() {
        let examples = load_examples(&spec_dir(), Suite::Gfm).expect("load GFM");
        assert_eq!(
            examples.len(),
            672,
            "spec/conformance.md records 672 GFM 0.29-gfm examples"
        );
        assert!(examples.iter().all(|e| e.number > 0));
    }

    #[test]
    fn expected_failures_parse_for_both_suites() {
        let cm = load_expected_failures(&spec_dir(), Suite::CommonMark).expect("commonmark list");
        let gfm = load_expected_failures(&spec_dir(), Suite::Gfm).expect("gfm list");
        assert!(!cm.is_empty());
        assert!(!gfm.is_empty());
    }

    /// Every listed number must name a real example. A number that names
    /// nothing is either a typo or a fixture-version mismatch, and it silently
    /// weakens the ratchet by one example.
    #[test]
    fn every_listed_failure_names_a_real_example() {
        for suite in Suite::ALL {
            let listed = load_expected_failures(&spec_dir(), suite).expect("list");
            let numbers: BTreeSet<u32> = load_examples(&spec_dir(), suite)
                .expect("examples")
                .iter()
                .map(|e| e.number)
                .collect();
            let stale: Vec<u32> = listed.difference(&numbers).copied().collect();
            assert!(stale.is_empty(), "{suite}: stale listings {stale:?}");
        }
    }

    /// The floors are the M2 exit gate, restated from §9 and spec/conformance.md.
    /// Listed failures cap the achievable rate, so the list must leave room to
    /// clear the floor.
    #[test]
    fn expected_failure_lists_leave_room_above_the_floor() {
        for suite in Suite::ALL {
            let listed = load_expected_failures(&spec_dir(), suite)
                .expect("list")
                .len();
            let total = load_examples(&spec_dir(), suite).expect("examples").len();
            let ceiling = ((total - listed) as f64 / total as f64) * 100.0;
            assert!(
                ceiling >= suite.floor_percent(),
                "{suite}: {listed} listed failures cap the pass rate at {ceiling:.1} %, \
                 below the {:.1} % floor",
                suite.floor_percent()
            );
        }
    }

    /// M0 state, asserted so that the day it changes is the day someone reads
    /// spec/README.md and re-baselines deliberately.
    #[test]
    fn every_suite_is_skipped_at_m0() {
        for suite in Suite::ALL {
            let report = run_suite(&spec_dir(), suite).expect("run");
            assert!(
                report.everything_skipped(),
                "{suite} is no longer fully skipped — mt_md now renders. \
                 Re-baseline per spec/README.md and delete this test."
            );
            assert!(!report.is_ci_failure());
        }
    }
}
